### ISSUE TITLE
Research TMDB API

### ISSUE THREAD

**Issue by ReallyBoard123** [devhausleipzigacademy/camp10-midterm#10]
## Steps

- [x] Read through the `Introduction` and `Getting started` sections of the docs
- [x] Identify the correct endpoints for the information needed
- [x] Document your results in the comments of this issue
- [x] create a new file in this folder structure src/types/api.ts and make types for UpcomingMovies, Movie, MovieDetail, Person, Cast, Crew, and Credits

## Resources

- [Documentation](https://developers.themoviedb.org/3/getting-started/introduction)

## Hint

Can approach us if you feel that you are spending way too much time on this!

**Comment by pswu11** [comment]
hello @ReallyBoard123 may I take this one?

**Comment by pswu11** [comment]
API endpoints (WIP)

- genres of all the movies: https://api.themoviedb.org/3/genre/movie/list
- movie detail: https://api.themoviedb.org/3/movie/{movie_id}

**Comment by ReallyBoard123** [comment]
> #### API endpoints
> * list of now playing movies: `https://api.themoviedb.org/3/movie/upcoming` should be /now_playing

**Comment by pswu11** [comment]
> > #### API endpoints
> > 
> > * list of now playing movies: `https://api.themoviedb.org/3/movie/upcoming` should be /now_playing

let me correct that in the pull request
